Exercise 1: Import the numpy package under the name np

In [1]:
import numpy as np

Exercise 2: Given an array X. Calculate sine, cosine, and tangent of X, element-wise.
X = np.array([1, 45, 60, 90])

In [2]:
X = np.array([1, 45, 60, 90])
print(np.sin(X))
print(np.cos(X))
print(np.tan(X))

[ 0.84147098  0.85090352 -0.30481062  0.89399666]
[ 0.54030231  0.52532199 -0.95241298 -0.44807362]
[ 1.55740772  1.61977519  0.32004039 -1.99520041]


Exercise 3: Given an array X. Convert angles from radians to degrees.


In [3]:
X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
r1 = np.degrees(X)
r1

array([-180.,  -90.,   90.,  180.])

Exercise 4: Given an arrya X. Convert angles from degrees to radians.

In [4]:
X = np.array([-180., -90., 90., 180.])
r2 = np.radians(X)
r2

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

Exercise 5: Given an array X. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of X, element-wise.

In [5]:
X = np.array([-1., 0, 1.])
print(np.sinh(X))
print(np.cosh(X))
print(np.tanh(X))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


Exercise 6: Given an array X. Calculate the round, ceil, floor of X, element-wise

In [6]:
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])
r1 = np.round(X)
r2 = np.ceil(X)
r3 = np.floor(X)
print(r1)
print(r2)
print(r3)

[  4.   2.  44.  26.  -1. -10.  -7.]
[ 5.  3. 45. 26. -1. -9. -6.]
[  4.   2.  44.  25.  -2. -10.  -7.]


Exercise 7: Given an array X. Calculate the difference between neighboring elements, element-wise.¶


In [7]:
X = np.array([11, 13, 23, 45, 77])
print(np.diff(X))

[ 2 10 22 32]


Exercise 8: Given two arrays X and Y. Find the cross product.

In [8]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(np.cross(X,Y))

[-3  6 -3]


Exercise 9: Given two arrays X and Y. Find the dot product.

In [9]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(np.dot(X,Y))

32


Exercise 10: Given two arrays X and Y. Divide X by Y element-wise using divide, true_divide, floor_divide functions.

In [10]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(np.divide(X,Y))
print(np.true_divide(X,Y))
print(np.floor_divide(X,Y))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[0 0 0]


Exercise 11: Given two arrays X and Y. Compute $X^Y$, element-wise.

In [11]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(np.power(X,Y))

[  1  32 729]


Exercise 12: Given one array X and Y = 3. Compute the remainder of X / Y element-wise using remainder and fmod functions.

In [12]:
X = np.array([1, 2, 3])
Y = 3
print(np.remainder(X,Y))
print(np.fmod(X,Y))

[1 2 0]
[1 2 0]


Exercise 13: Given an array X. If an element of X is smaller than 5, replace it with 4. And if an element of X is bigger than 9, replace it with 8.

In [13]:
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
X[X < 5] = 4
X[X > 9] = 8
print(X)

[8 4 8 4 8 8 4 5]


Exercise 14: Given an array X. Compute the square of X, element-wise.

In [14]:
X = np.array([2, 3, 4, 5, 6])
print(np.square(X))

[ 4  9 16 25 36]


Exercise 15: Given an array X. Compute the absolute value of X.

In [15]:
X = np.array([[-44, 3], [4, -3]])
print(np.abs(X))

[[44  3]
 [ 4  3]]


Exercise 16: Given an array X. Compute an element-wise indication of the sign of X, element-wise.

In [16]:
X = np.array([1, 3, 0, -1, -3])
r1 = np.sign(X)
r1

array([ 1,  1,  0, -1, -1])

Exercise 17: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [17]:
np.random.rand(0,1)


array([], shape=(0, 1), dtype=float64)

Exercise 18: Given an array gaussian. How do you get the number of dimensions of the array?

In [18]:

gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(gaussian.ndim)

3


Exercise 19: Given an array gaussian. How do you get the shape of an array?

In [19]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(gaussian.shape)


(2, 3, 4)


Exercise 20: Given an array gaussian. How do you get the total number of elements in the array?

In [20]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(gaussian.size)

24


Exercise 21: Given an array gaussian. How do you get memory consumed by each item in the array?

In [21]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(gaussian.itemsize)

8


Exercise 22: Given an array twenty. How do you access first two rows and three columns

In [22]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
print(twenty[:2,:3])

[[0 1 2]
 [5 6 7]]


Exercise 23: Given an array twenty. How do you reverse the order of elements along columns?

In [23]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
print(np.flip(twenty,axis=1))

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


Exercise 24: Given an array twenty. How do you reverse the order of elements along rows?

In [24]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
print(np.flip(twenty,axis=0))

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


Exercise 25: Given an array twenty. How do you shuffle the array along axis - 0